## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentShema=demo
    username: postgres
    password: Welcome1!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialet: org.hibarnate.dialet.PostgreSQLDialect
        format_sql: true
servelet:
  multipart:
    enable: true
    max-file-size: 1000MB
    max-request-size: 1000MB
mvc:
  throw-exception-if-no-handler-found: true
  async:
    request-timeout: 3600000
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enable: false
